extends SceneTree

# Find contiguous Y segments for a given X coordinate
func get_contiguous_y_segments(y_coords: Array) -> Array:
	y_coords = y_coords.duplicate()
	y_coords.sort()
	var segments: Array = []
	if y_coords.size() == 0:
		return segments
	
	var current_segment: Array = [y_coords[0]]
	for i in range(1, y_coords.size()):
		if y_coords[i] == y_coords[i-1] + 1:
			current_segment.append(y_coords[i])
		else:
			segments.append(current_segment)
			current_segment = [y_coords[i]]
	segments.append(current_segment)
	return segments

func _init() -> void:
	var base64_data := "AAAMAP//FAANAA4AAAAGAP//FAAPAA4AAAAFAP//FAAKAA4AAAD9////FAADAAIAAAAVAP//FAAOAA4AAAD8/wAAAgANAAsAACD8/zIAAgAAAAAAAAD8/zMAAgAAAAAAAAD8/zQAAgAAAAAAAAD9/wAAAgAMAAsAAAD9/zIAAgAAAAAAAAD9/zMAAgAAAAAAAAD9/zQAAgAAAAAAAAD+/wAAAgANAAsAAAD+/zIAAgAKAA4AACD+/zMAAgAAAAAAAAD+/zQAAgAAAAAAAAD//wAAAgAJAAsAAAD//zIAAgAEABYAAAD//zMAAgAAAAAAAAD//zQAAgAAAAAAAAAAAAAAAgAMAAsAAAAAADIAAgAAAAAAAAAAADMAAgAAAAAAAAAAADQAAgAAAAAAAAABAAAAAgAJAAAAACABADIAAgAMAA0AAAABADMAAgAAAAAAAAABADQAAgAAAAAAAAACAAAAAgALAAsAAAACADIAAgAAAAAAAAACADMAAgAAAAAAAAACADQAAgAAAAAAAAADAAAAAgAOAAkAAGADADIAAgAAABgAAAADADMAAgAFAAkAAGADADQAAgAAAAAAAAAEAAAAAgAIAAcAAAAEADIAAgAAAAAAAAAEADMAAgAAAAAAAAAEADQAAgAAAAAAAAAFAAAAAgAIAAcAAAAFADIAAgAAAAAAAAAFADMAAgAAAAAAAAAFADQAAgAAAAAAAAAGAAAAAgAJAAAAACAGADIAAgALAA0AAAAGADMAAgAAAAAAAAAGADQAAgAAAAAAAAAGAAIAAgAAAAAAAAAGAAMAAgAAAAAAAAAHAAAAAgAJAAIAAAAHADIAAgAGAA4AAAAHADMAAgAAAAAAAAAHADQAAgAAAAAAAAAHAAMAAgAAAAAAAAAIAAAAAgAIAAcAAAAIAAEAAgAAAAAAAAAIAAIAAgAAAAAAAAAIAAMAAgAAAAAAAAAJAAAAAgAOAAcAAAAJAAEAAgAAAAAAAAAJAAIAAgAAAAAAAAAJAAMAAgAAAAAAAAAKAAAAAgAKAAsAAHAKAAEAAgAHABAAACAKAAIAAgAAAAAAAAAKAAMAAgAAAAAAAAALAAAAAgAGABYAACALAAEAAgAAAAAAAAALAAIAAgAAAAAAAAALAAMAAgAAAAAAAAAMAAAAAgAHABYAACAMAAEAAgAAAAAAAAAMAAIAAgAAAAAAAAAMAAMAAgAAAAAAAAANAAAAAgAJAAEAAAANAAEAAgAKAAoAACANAAIAAgAAAAAAAAANAAMAAgAAAAAAAAAOAAAAAgAJABYAACAOAAEAAgAAAAAAAAAOAAIAAgAAAAAAAAAOAAMAAgAAAAAAAAAPAAAAAgAKABYAACAPAAEAAgAAAAAAAAAPAAIAAgAAAAAAAAAPAAMAAgAAAAAAAAAQAAAAAgAOAAcAAAAQAAEAAgAAAAAAAAAQAAIAAgAAAAAAAAAQAAMAAgAAAAAAAAARAAAAAgANAAsAACARAAEAAgAAAAAAAAARAAIAAgAAAAAAAAARAAMAAgAAAAAAAAASAAAAAgAIAAcAAAASAAEAAgAAAAAAAAASAAIAAgAAAAAAAAASAAMAAgAAAAAAAAATAAAAAgAGABYAACATAAEAAgAAAAAAAAATAAIAAgAAAAAAAAATAAMAAgAAAAAAAAAUAAAAAgAHABYAACAUAAEAAgAAAAAAAAAUAAIAAgAAAAAAAAAUAAMAAgAAAAAAAAAVAAAAAgAJABYAACAVAAEAAgAHABQAACAVAAIAAgAAAAAAAAAVAAMAAgAAAAAAAAAWAAAAAgAKABYAACAWAAEAAgAIABQAACAWAAIAAgAAAAAAAAAWAAMAAgAAAAAAAAAXAAAAAgALABYAACAXAAEAAgAAAAAAAAAXAAIAAgAAAAAAAAAXAAMAAgAAAAAAAAAYAAAAAgAJAAIAAAAYAAEAAgAAAAAAAAAYAAIAAgAAAAAAAAAYAAMAAgAAAAAAAAAGAAAAAgAMAAsAAAAZAAEAAgAAAAAAAAAZAAIAAgAAAAAAAAAZAAMAAgAAAAAAAAD2/wAAAgALAAAAACD2/zIAAgAAAAAAAAD2/zMAAgAAAAAAAAD2/zQAAgAAAAAAAAD3/wAAAgAJAAIAAAD3/zIAAgAAAAAAAAD3/zMAAgAAAAAAAAD3/zQAAgAAAAAAAAD4/wAAAgAIAAcAAAD4/zIAAgAAAAAAAAD4/zMAAgAAAAAAAAD4/zQAAgAAAAAAAAD5/wAAAgAKAAEAAED5/zIAAgAAAAAAAAD5/zMAAgAAAAAAAAD5/zQAAgAAAAAAAAD6/wAAAgAJAAIAAAD6/zIAAgAAAAAAAAD6/zMAAgAAAAAAAAD6/zQAAgAAAAAAAAD7/wAAAgAIAAEAAHD7/zIAAgAAAAAAAAD7/zMAAgAAAAAAAAD7/zQAAgAAAAAAAAD0////FAANAA4AABDr////FAAOAA4AABD1/wAAAgAGABYAADD0/wAAAgAHABYAADDz/wAAAgAJAAEAABDy/wAAAgAJABYAADDx/wAAAgAKABYAADDw/wAAAgAOAAcAABDv/wAAAgANAAsAADDu/wAAAgAIAAcAABDt/wAAAgAGABYAADDs/wAAAgAHABYAADDr/wAAAgAJABYAADDq/wAAAgAKABYAADDp/wAAAgALABYAADDo/wAAAgAJAAIAABDn/wAAAgAIAAcAABD1/zIAAgAAAAAAABD0/zIAAgAAAAAAABDz/zIAAgAKAAoAADDy/zIAAgAAAAAAABDx/zIAAgAAAAAAABDw/zIAAgAAAAAAABDv/zIAAgAAAAAAABDu/zIAAgAAAAAAABDt/zIAAgAAAAAAABDs/zIAAgAAAAAAABDr/zIAAgAHABQAADDq/zIAAgAIABQAADDp/zIAAgAAAAAAABDo/zIAAgAAAAAAABDn/zIAAgAAAAAAABD1/zMAAgAAAAAAABD0/zMAAgAAAAAAABDz/zMAAgAAAAAAABDy/zMAAgAAAAAAABDx/zMAAgAAAAAAABDw/zMAAgAAAAAAABDv/zMAAgAAAAAAABDu/zMAAgAAAAAAABDt/zMAAgAAAAAAABDs/zMAAgAAAAAAABDr/zMAAgAAAAAAABDq/zMAAgAAAAAAABDp/zMAAgAAAAAAABDo/zMAAgAAAAAAABDn/zMAAgAAAAAAABD1/zQAAgAAAAAAABD0/zQAAgAAAAAAABDz/zQAAgAAAAAAABDy/zQAAgAAAAAAABDx/zQAAgAAAAAAABDw/zQAAgAAAAAAABDv/zQAAgAAAAAAABDu/zQAAgAAAAAAABDt/zQAAgAAAAAAABDs/zQAAgAAAAAAABDr/zQAAgAAAAAAABDq/zQAAgAAAAAAABDp/zQAAgAAAAAAABDo/zQAAgAAAAAAABDn/zQAAgAAAAAAABAaAAAAAgANAAsAAAAaADIAAgAKAA4AACAaADMAAgAAAAAAAAAaADQAAgAAAAAAAAAbAAAAAgAJAAsAAAAbADIAAgAEABYAAAAbADMAAgAAAAAAAAAbADQAAgAAAAAAAAAcAAAAAgAMAAsAAAAcADIAAgAFABYAAAAcADMAAgAAAAAAAAAcADQAAgAAAAAAAAAdAAAAAgAJAAAAACAdADIAAg AMAA0AAAAdADMAAgAAAAAAAAAdADQAAgAAAAAAAAAeAAAAAgAOAAcAABAeADIAAgAAAAAAABAeADMAAgAAAAAAABAeADQAAgAAAAAAABAfAAAAAgAKABYAADAfADIAAgAAAAAAABAfADMAAgAAAAAAABAfADQAAgAAAAAAABAjAAAAAgAGABYAADAiAAAAAgAHABYAADAhAAAAAgAJAAEAABAgAAAAAgAJABYAADAjADIAAgAAAAAAABAiADIAAgAAAAAAABAhADIAAgAKAAoAADAgADIAAgAAAAAAABAjADMAAgAAAAAAABAiADMAAgAAAAAAABAhADMAAgAAAAAAABAgADMAAgAAAAAAABAjADQAAgAAAAAAABAiADQAAgAAAAAAABAhADQAAgAAAAAAABAgADQAAgAAAAAAABAqAAAAAgAJAAIAABApAAAAAgAMAAsAABAoAAAAAgANAAsAABAnAAAAAgANAAsAABAmAAAAAgAMAAsAABAlAAAAAgAJAAAAADAkAAAAAgAOAAcAAAAqADIAAgAAAAAAABApADIAAgAAAAAAABAoADIAAgAKAA4AADAnADIAAgAJAA4AAAAmADIAAgAAAAAAAAAlADIAAgAMAA0AABAkADIAAgAAAAAAAAAqADMAAgAAAAAAABApADMAAgAAAAAAABAoADMAAgAAAAAAABAnADMAAgAAAAAAABAmADMAAgAAAAAAABAlADMAAgAAAAAAABAkADMAAgAAAAAAAAAqADQAAgAAAAAAABApADQAAgAAAAAAABAoADQAAgAAAAAAABAnADQAAgAAAAAAABAmADQAAgAAAAAAABAlADQAAgAAAAAAABAkADQAAgAAAAAAAAA="
	
	# Let's inspect the binary layout decodes
	var byte_data := Marshalls.base64_to_raw(base64_data)
	var world_layer := TileMapLayer.new()
	world_layer.tile_map_data = byte_data
	
	var cells := world_layer.get_used_cells()
	print("Cells count: ", cells.size())
	
	var coords_by_x: Dictionary = {}
	for cell in cells:
		if not coords_by_x.has(cell.x):
			coords_by_x[cell.x] = []
		coords_by_x[cell.x].append(cell.y)
		
	var cell_sources: Dictionary = {}
	for x in coords_by_x.keys():
		var y_list = coords_by_x[x]
		var segments = get_contiguous_y_segments(y_list)
		if x == -21:
			print("X = -21 segments: ", segments)
		for segment in segments:
			var top_y = segment[0]
			cell_sources[Vector2i(x, top_y)] = 20
			for idx in range(1, segment.size()):
				cell_sources[Vector2i(x, segment[idx])] = 2
				
	# Check cell (-21, 0)
	print("Cell (-21, 0) target: ", cell_sources.get(Vector2i(-21, 0)))
	print("Cell (-21, 50) target: ", cell_sources.get(Vector2i(-21, 50)))
	
	quit(0)
